version: "3"

services:

  eth_bootnode:
    hostname: bootnode
    environment:
      - key=0acd3e0043e73c4bf95187c935fb7d6cc688685f1da60fb72da1d588ffca13f5
    build:
      context: ./bootnode
    ports:
      - 30301:30301/udp
    networks:
      eth_private_network:
        ipv4_address: 172.28.1.10


  eth_miner1:
    restart: on-failure:5
    hostname: miner1
    depends_on:
      - eth_bootnode
    environment:
      - addr=0xa7EfD857De41dc223Cfc8cf6FE052348492864C4
      - id=4cb7dc25aaeb769ae94ce002e2ecd5232d9421a81c3cc63620a79db127778dd89c61348e7475a1e977cb72121098d364451bcbbaffd2981e306408d4b2405a6e
      - ip=172.28.1.10
    build:
      context: ./miner
      args:
        pk: 91fa188e5e01a3ba4df713c97e1b712a878451db3952fc104f7eb90e9f860e0c # BIP39 Mnemonic: panel average amount abandon fence renew spoon powder top grid whip achieve access sponsor meadow
        pwd: 9Uk5kskVGZdTsu87 # 9 USA korean 5 korean skype korean VISA GOLF ZIP drip TOKYO skype usa 8 7
    container_name: miner1
    ports:
      # http port
      - 8545:59767
    volumes:
     - eth_data_miner1:/root/.ethash
    networks:
      eth_private_network:
        ipv4_address: 172.28.1.12

  eth_miner4:
    restart: on-failure:5
    hostname: miner4
    depends_on:
      - eth_bootnode
    environment:
      - addr=0xbcD3dF4be3f1A5A31D67B631299081f3a6eaB254
      - id=4cb7dc25aaeb769ae94ce002e2ecd5232d9421a81c3cc63620a79db127778dd89c61348e7475a1e977cb72121098d364451bcbbaffd2981e306408d4b2405a6e
      - ip=172.28.1.10
    build:
      context: ./miner
      args:
        pk: fda7f055ae33f31ec504c210e7190bbeb49467c8f3427a6af425a42bfbeb59b6
        pwd: hello01 # 9 USA korean 5 korean skype korean VISA GOLF ZIP drip TOKYO skype usa 8 7
    container_name: miner4
    ports:
      # http port
      - 8548:59767
    volumes:
     - eth_data_miner4:/root/.ethash
    networks:
      eth_private_network:
        ipv4_address: 172.28.1.13

  eth_miner5:
    restart: on-failure:5
    hostname: miner5
    depends_on:
      - eth_bootnode
    environment:
      - addr=0x87CDF88B1791656c338a266a6f216A68FC60F877
      - id=4cb7dc25aaeb769ae94ce002e2ecd5232d9421a81c3cc63620a79db127778dd89c61348e7475a1e977cb72121098d364451bcbbaffd2981e306408d4b2405a6e
      - ip=172.28.1.10
    build:
      context: ./miner
      args:
        pk: 816c3fd94b42814a4f750bafc6b2b32a6c065f28a8eeca92ac59c7ccd0271d4a
        pwd: hello01 # 9 USA korean 5 korean skype korean VISA GOLF ZIP drip TOKYO skype usa 8 7
    container_name: miner5
    ports:
      # http port
      - 8549:59767
    volumes:
     - eth_data_miner5:/root/.ethash
    networks:
      eth_private_network:
        ipv4_address: 172.28.1.14

  eth_miner2:
    restart: on-failure:5
    hostname: miner2
    depends_on:
      - eth_bootnode
    environment:
      - addr=0x116C95B6f0599b80EdaEF96dB4A0a03890bAf812
      - id=4cb7dc25aaeb769ae94ce002e2ecd5232d9421a81c3cc63620a79db127778dd89c61348e7475a1e977cb72121098d364451bcbbaffd2981e306408d4b2405a6e
      - ip=172.28.1.10
    build:
      context: ./miner
      args:
        pk: 1646b6552c0bcea3fda9001bf5748a53a0499c724f4f60ec1038ad76d9c5d861 # BIP39 Mnemonic: limb pair transfer answer flower rescue inquiry quit debate echo liquid owner priority require again
        pwd: 6Z39urGJgqxjJWjQ # 6 ZIP 3 9 usa rope GOLF JACK golf queen xbox jack JACK WALMART jack QUEEN
    container_name: miner2
    ports:
      # http port
      - 8546:59767
    volumes:
      - eth_data_miner2:/root/.ethash
    networks:
      eth_private_network:
        ipv4_address: 172.28.1.15

  eth_miner3:
    restart: on-failure:5
    hostname: miner3
    depends_on:
      - eth_bootnode
    environment:
      - addr=0xe062C6acEF6e44a009dfF67bCBdDf2C780DdbC91
      - id=4cb7dc25aaeb769ae94ce002e2ecd5232d9421a81c3cc63620a79db127778dd89c61348e7475a1e977cb72121098d364451bcbbaffd2981e306408d4b2405a6e
      - ip=172.28.1.10
    build:
      context: ./miner
      args:
        pk: 7641fd2a79042e9bb78d5a5960d6c32afcbeda6e5c4076262db3263bd7d5de27 # BIP39 Mnemonic: toy paper favorite position stumble broccoli enhance purse nerve fat hobby size improve pumpkin truck
        pwd: MfeLN6JxcZ6P25eC # MUSIC fruit egg LAPTOP NUT 6 JACK xbox coffee ZIP 6 PARK 2 5 egg COFFEE
    container_name: miner3
    ports:
      # http port
      - 8547:59767
    volumes:
      - eth_data_miner3:/root/.ethash
    networks:
      eth_private_network:
        ipv4_address: 172.28.1.11



networks:
  eth_private_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.1.0/24

volumes:
  eth_data_miner1:
  eth_data_miner2:
  eth_data_miner3:
  eth_data_miner4:
  eth_data_miner5:


